version: "3.3"

services:
  mariadb-nmo:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb-nmo
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_USER=root
      - TZ=America/Los_Angeles
    volumes:
      - ./.db:/config
    ports:
      - "5100:3306"
    restart: unless-stopped
    networks:
      - network

  baseball:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseball
    depends_on:
      - mariadb-nmo
    restart: "no"
    volumes:
      - ./output:/output
    ports:
      - "5101:3307"
    networks:
      - network

networks:
  network:
